### ISSUE TITLE
Incompatible with ruby 3.2.x

### ISSUE THREAD

**Issue by exaos** [taskjuggler/TaskJuggler#282]
I cannot run TaskJuggler 3.7.1 after upgrading my ruby to 3.2.x. The error message is as below:

```
tj3 tutorial.tjp
TaskJuggler v3.7.1 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020
              by Chris Schlaeger <cs@taskjuggler.org>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Fatal: undefined method `untaint' for "tutorial.tjp":String
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/TextParser/Scanner.rb:172:in `initialize'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/TextParser/Scanner.rb:293:in `new'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/TextParser/Scanner.rb:293:in `open'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/ProjectFileParser.rb:58:in `open'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/TaskJuggler.rb:57:in `block in parse'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/TaskJuggler.rb:55:in `each'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/TaskJuggler.rb:55:in `parse'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/apps/Tj3.rb:187:in `appMain'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/taskjuggler/Tj3AppBase.rb:160:in `main'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/lib/tj3.rb:16:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
/Users/vivodo/.local/share/gem/ruby/3.2.0/gems/taskjuggler-3.7.1/bin/tj3:4:in `<top (required)>'
/Users/vivodo/.local/share/gem/ruby/3.2.0/bin/tj3:25:in `load'
/Users/vivodo/.local/share/gem/ruby/3.2.0/bin/tj3:25:in `<main>'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.7.1!
Please see the user manual on how to get this bug fixed!
http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
*******************************************************************************
```

Ruby 3.2.0 has removed some deprecated methods (taint/trust/untaint/untrust) ,ref: https://bugs.ruby-lang.org/issues/16131 .

**Comment by exaos** [comment]
This issue is solved in version 3.7.2. Thanks!
